#!/bin/bash -l

export lrank=$OMPI_COMM_WORLD_LOCAL_RANK

export APP=./lpi_head_single_new_diag.Linux

case ${lrank} in
[0])
  export CUDA_VISIBLE_DEVICES=0
  $APP
  ;;
[1])
  export CUDA_VISIBLE_DEVICES=0
  $APP
  ;;
[2])
  export CUDA_VISIBLE_DEVICES=1
  $APP
  ;;
[3])
  export CUDA_VISIBLE_DEVICES=1
  $APP
  ;;
[4])
  export CUDA_VISIBLE_DEVICES=2
  $APP
  ;;
[5])
  export CUDA_VISIBLE_DEVICES=2
  $APP
  ;;
[6])
  export CUDA_VISIBLE_DEVICES=3
  $APP
  ;;
[7])
  export CUDA_VISIBLE_DEVICES=3
  $APP
  ;;
esac

